#!/bin/bash
#

pushd data

rrdtool graph temp1.png -w 600 -h 250 --start -3hours --end now --title "test combined" \
								DEF:ok=all-test-yesno.rrd:ok:AVERAGE \
								DEF:fail=all-test-yesno.rrd:fail:AVERAGE \
								AREA:ok#AAFFAA:STACK \
								AREA:fail#FFAAAA:STACK \
								LINE1:ok#737373

rrdtool graph temp2.png -w 600 -h 250 --start -3hours --end now --title "test successes" \
								DEF:ok=all-test-yesno.rrd:ok:AVERAGE \
								DEF:fail=all-test-yesno.rrd:fail:AVERAGE \
								AREA:ok#AAFFAA \
								LINE1:ok#797979

rrdtool graph temp3.png -w 600 -h 250 --start -3hours --end now --title "test failures" \
								DEF:ok=all-test-yesno.rrd:ok:AVERAGE \
								DEF:fail=all-test-yesno.rrd:fail:AVERAGE \
								AREA:fail#FFAAAA \
								LINE1:fail#797979

rrdtool graph temp4.png -w 800 -h 350 --start -3hours --end now -l 0 --title "query" \
								DEF:lo=all-query-quartiles.rrd:lo:AVERAGE \
								DEF:hi=all-query-quartiles.rrd:hi:AVERAGE \
								DEF:q1=all-query-quartiles.rrd:q1:AVERAGE \
								DEF:q2=all-query-quartiles.rrd:q2:AVERAGE \
								DEF:q3=all-query-quartiles.rrd:q3:AVERAGE \
								AREA:q3#FFAAAA \
								AREA:q2#AAFFAA \
								AREA:q1#DDFFDD \
								AREA:lo#FFFFFF \
								LINE1:q2#797979

rrdtool graph temp5.png -w 800 -h 350 --start -3hours --end now -l 0 --title "value" \
								DEF:lo=all-value-quartiles.rrd:lo:AVERAGE \
								DEF:hi=all-value-quartiles.rrd:hi:AVERAGE \
								DEF:q1=all-value-quartiles.rrd:q1:AVERAGE \
								DEF:q2=all-value-quartiles.rrd:q2:AVERAGE \
								DEF:q3=all-value-quartiles.rrd:q3:AVERAGE \
								AREA:q3#F89D98 \
								AREA:q2#95F19A \
								AREA:q1#DDFFDE \
								AREA:lo#FFFFFF \
								LINE1:q2#797979

rrdtool graph temp6.png -w 800 -h 350 --start -3hours --end now -l 0 --title "jacob" \
								DEF:lo=all-jacob-quartiles.rrd:lo:AVERAGE \
								DEF:hi=all-jacob-quartiles.rrd:hi:AVERAGE \
								DEF:q1=all-jacob-quartiles.rrd:q1:AVERAGE \
								DEF:q2=all-jacob-quartiles.rrd:q2:AVERAGE \
								DEF:q3=all-jacob-quartiles.rrd:q3:AVERAGE \
								AREA:q3#F89D98 \
								AREA:q2#95F19A \
								AREA:q1#DDFFDE \
								AREA:lo#FFFFFF \
								LINE1:q2#797979

rrdtool graph temp7.png -w 800 -h 350 --start -3hours --end now -l 0 --title "andy" \
								DEF:lo=all-andy-quartiles.rrd:lo:AVERAGE \
								DEF:hi=all-andy-quartiles.rrd:hi:AVERAGE \
								DEF:q1=all-andy-quartiles.rrd:q1:AVERAGE \
								DEF:q2=all-andy-quartiles.rrd:q2:AVERAGE \
								DEF:q3=all-andy-quartiles.rrd:q3:AVERAGE \
								AREA:q3#F89D98 \
								AREA:q2#95F19A \
								AREA:q1#DDFFDE \
								AREA:lo#FFFFFF \
								LINE1:q2#797979

mv *.png /var/www/graphs
rm -rf /var/www/graphs/index.html
for a in /var/www/graphs/*.png; do
  file=`basename $a`
  echo "<img src='$file' />" >> /var/www/graphs/index.html
done
popd
