#!/bin/bash

pushd data
rm -rf /var/www/graphs/*
mv *.png /var/www/graphs
for a in /var/www/graphs/*.png; do
  file=`basename $a`
  echo "<img src='$file' />" >> /var/www/graphs/index.html
done
popd

